# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /data/data/com.termux/files/usr/bin/sh

# The CMake executable.
CMAKE_COMMAND = /data/data/com.termux/files/usr/bin/cmake

# The command to remove a file.
RM = /data/data/com.termux/files/usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/data/com.termux/files/home/source/ffmpegthumbnailer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/data/com.termux/files/home/source/ffmpegthumbnailer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/data/data/com.termux/files/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/data/data/com.termux/files/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/data/data/com.termux/files/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/data/data/com.termux/files/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/data/data/com.termux/files/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/data/data/com.termux/files/usr/bin/cpack --config ./CPackSourceConfig.cmake /data/data/com.termux/files/home/source/ffmpegthumbnailer/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/data/data/com.termux/files/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/data/data/com.termux/files/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/data/data/com.termux/files/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/data/data/com.termux/files/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/data/data/com.termux/files/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/source/ffmpegthumbnailer/CMakeFiles /data/data/com.termux/files/home/source/ffmpegthumbnailer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/source/ffmpegthumbnailer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libffmpegthumbnailer

# Build rule for target.
libffmpegthumbnailer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libffmpegthumbnailer
.PHONY : libffmpegthumbnailer

# fast build rule for target.
libffmpegthumbnailer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailer.dir/build.make CMakeFiles/libffmpegthumbnailer.dir/build
.PHONY : libffmpegthumbnailer/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named ffmpegthumbnailer

# Build rule for target.
ffmpegthumbnailer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ffmpegthumbnailer
.PHONY : ffmpegthumbnailer

# fast build rule for target.
ffmpegthumbnailer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpegthumbnailer.dir/build.make CMakeFiles/ffmpegthumbnailer.dir/build
.PHONY : ffmpegthumbnailer/fast

#=============================================================================
# Target rules for targets named libffmpegthumbnailerobj

# Build rule for target.
libffmpegthumbnailerobj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libffmpegthumbnailerobj
.PHONY : libffmpegthumbnailerobj

# fast build rule for target.
libffmpegthumbnailerobj/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/build
.PHONY : libffmpegthumbnailerobj/fast

#=============================================================================
# Target rules for targets named ffmpegthumbnailerctest

# Build rule for target.
ffmpegthumbnailerctest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ffmpegthumbnailerctest
.PHONY : ffmpegthumbnailerctest

# fast build rule for target.
ffmpegthumbnailerctest/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/ffmpegthumbnailerctest.dir/build.make test/CMakeFiles/ffmpegthumbnailerctest.dir/build
.PHONY : ffmpegthumbnailerctest/fast

#=============================================================================
# Target rules for targets named ffmpegthumbnailertest

# Build rule for target.
ffmpegthumbnailertest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ffmpegthumbnailertest
.PHONY : ffmpegthumbnailertest

# fast build rule for target.
ffmpegthumbnailertest/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/ffmpegthumbnailertest.dir/build.make test/CMakeFiles/ffmpegthumbnailertest.dir/build
.PHONY : ffmpegthumbnailertest/fast

libffmpegthumbnailer/filmstripfilter.o: libffmpegthumbnailer/filmstripfilter.cpp.o
.PHONY : libffmpegthumbnailer/filmstripfilter.o

# target to build an object file
libffmpegthumbnailer/filmstripfilter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/filmstripfilter.cpp.o
.PHONY : libffmpegthumbnailer/filmstripfilter.cpp.o

libffmpegthumbnailer/filmstripfilter.i: libffmpegthumbnailer/filmstripfilter.cpp.i
.PHONY : libffmpegthumbnailer/filmstripfilter.i

# target to preprocess a source file
libffmpegthumbnailer/filmstripfilter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/filmstripfilter.cpp.i
.PHONY : libffmpegthumbnailer/filmstripfilter.cpp.i

libffmpegthumbnailer/filmstripfilter.s: libffmpegthumbnailer/filmstripfilter.cpp.s
.PHONY : libffmpegthumbnailer/filmstripfilter.s

# target to generate assembly for a file
libffmpegthumbnailer/filmstripfilter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/filmstripfilter.cpp.s
.PHONY : libffmpegthumbnailer/filmstripfilter.cpp.s

libffmpegthumbnailer/jpegwriter.o: libffmpegthumbnailer/jpegwriter.cpp.o
.PHONY : libffmpegthumbnailer/jpegwriter.o

# target to build an object file
libffmpegthumbnailer/jpegwriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/jpegwriter.cpp.o
.PHONY : libffmpegthumbnailer/jpegwriter.cpp.o

libffmpegthumbnailer/jpegwriter.i: libffmpegthumbnailer/jpegwriter.cpp.i
.PHONY : libffmpegthumbnailer/jpegwriter.i

# target to preprocess a source file
libffmpegthumbnailer/jpegwriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/jpegwriter.cpp.i
.PHONY : libffmpegthumbnailer/jpegwriter.cpp.i

libffmpegthumbnailer/jpegwriter.s: libffmpegthumbnailer/jpegwriter.cpp.s
.PHONY : libffmpegthumbnailer/jpegwriter.s

# target to generate assembly for a file
libffmpegthumbnailer/jpegwriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/jpegwriter.cpp.s
.PHONY : libffmpegthumbnailer/jpegwriter.cpp.s

libffmpegthumbnailer/moviedecoder.o: libffmpegthumbnailer/moviedecoder.cpp.o
.PHONY : libffmpegthumbnailer/moviedecoder.o

# target to build an object file
libffmpegthumbnailer/moviedecoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/moviedecoder.cpp.o
.PHONY : libffmpegthumbnailer/moviedecoder.cpp.o

libffmpegthumbnailer/moviedecoder.i: libffmpegthumbnailer/moviedecoder.cpp.i
.PHONY : libffmpegthumbnailer/moviedecoder.i

# target to preprocess a source file
libffmpegthumbnailer/moviedecoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/moviedecoder.cpp.i
.PHONY : libffmpegthumbnailer/moviedecoder.cpp.i

libffmpegthumbnailer/moviedecoder.s: libffmpegthumbnailer/moviedecoder.cpp.s
.PHONY : libffmpegthumbnailer/moviedecoder.s

# target to generate assembly for a file
libffmpegthumbnailer/moviedecoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/moviedecoder.cpp.s
.PHONY : libffmpegthumbnailer/moviedecoder.cpp.s

libffmpegthumbnailer/pngwriter.o: libffmpegthumbnailer/pngwriter.cpp.o
.PHONY : libffmpegthumbnailer/pngwriter.o

# target to build an object file
libffmpegthumbnailer/pngwriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/pngwriter.cpp.o
.PHONY : libffmpegthumbnailer/pngwriter.cpp.o

libffmpegthumbnailer/pngwriter.i: libffmpegthumbnailer/pngwriter.cpp.i
.PHONY : libffmpegthumbnailer/pngwriter.i

# target to preprocess a source file
libffmpegthumbnailer/pngwriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/pngwriter.cpp.i
.PHONY : libffmpegthumbnailer/pngwriter.cpp.i

libffmpegthumbnailer/pngwriter.s: libffmpegthumbnailer/pngwriter.cpp.s
.PHONY : libffmpegthumbnailer/pngwriter.s

# target to generate assembly for a file
libffmpegthumbnailer/pngwriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/pngwriter.cpp.s
.PHONY : libffmpegthumbnailer/pngwriter.cpp.s

libffmpegthumbnailer/rgbwriter.o: libffmpegthumbnailer/rgbwriter.cpp.o
.PHONY : libffmpegthumbnailer/rgbwriter.o

# target to build an object file
libffmpegthumbnailer/rgbwriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/rgbwriter.cpp.o
.PHONY : libffmpegthumbnailer/rgbwriter.cpp.o

libffmpegthumbnailer/rgbwriter.i: libffmpegthumbnailer/rgbwriter.cpp.i
.PHONY : libffmpegthumbnailer/rgbwriter.i

# target to preprocess a source file
libffmpegthumbnailer/rgbwriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/rgbwriter.cpp.i
.PHONY : libffmpegthumbnailer/rgbwriter.cpp.i

libffmpegthumbnailer/rgbwriter.s: libffmpegthumbnailer/rgbwriter.cpp.s
.PHONY : libffmpegthumbnailer/rgbwriter.s

# target to generate assembly for a file
libffmpegthumbnailer/rgbwriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/rgbwriter.cpp.s
.PHONY : libffmpegthumbnailer/rgbwriter.cpp.s

libffmpegthumbnailer/stringoperations.o: libffmpegthumbnailer/stringoperations.cpp.o
.PHONY : libffmpegthumbnailer/stringoperations.o

# target to build an object file
libffmpegthumbnailer/stringoperations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/stringoperations.cpp.o
.PHONY : libffmpegthumbnailer/stringoperations.cpp.o

libffmpegthumbnailer/stringoperations.i: libffmpegthumbnailer/stringoperations.cpp.i
.PHONY : libffmpegthumbnailer/stringoperations.i

# target to preprocess a source file
libffmpegthumbnailer/stringoperations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/stringoperations.cpp.i
.PHONY : libffmpegthumbnailer/stringoperations.cpp.i

libffmpegthumbnailer/stringoperations.s: libffmpegthumbnailer/stringoperations.cpp.s
.PHONY : libffmpegthumbnailer/stringoperations.s

# target to generate assembly for a file
libffmpegthumbnailer/stringoperations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/stringoperations.cpp.s
.PHONY : libffmpegthumbnailer/stringoperations.cpp.s

libffmpegthumbnailer/videothumbnailer.o: libffmpegthumbnailer/videothumbnailer.cpp.o
.PHONY : libffmpegthumbnailer/videothumbnailer.o

# target to build an object file
libffmpegthumbnailer/videothumbnailer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/videothumbnailer.cpp.o
.PHONY : libffmpegthumbnailer/videothumbnailer.cpp.o

libffmpegthumbnailer/videothumbnailer.i: libffmpegthumbnailer/videothumbnailer.cpp.i
.PHONY : libffmpegthumbnailer/videothumbnailer.i

# target to preprocess a source file
libffmpegthumbnailer/videothumbnailer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/videothumbnailer.cpp.i
.PHONY : libffmpegthumbnailer/videothumbnailer.cpp.i

libffmpegthumbnailer/videothumbnailer.s: libffmpegthumbnailer/videothumbnailer.cpp.s
.PHONY : libffmpegthumbnailer/videothumbnailer.s

# target to generate assembly for a file
libffmpegthumbnailer/videothumbnailer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/videothumbnailer.cpp.s
.PHONY : libffmpegthumbnailer/videothumbnailer.cpp.s

libffmpegthumbnailer/videothumbnailerc.o: libffmpegthumbnailer/videothumbnailerc.cpp.o
.PHONY : libffmpegthumbnailer/videothumbnailerc.o

# target to build an object file
libffmpegthumbnailer/videothumbnailerc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/videothumbnailerc.cpp.o
.PHONY : libffmpegthumbnailer/videothumbnailerc.cpp.o

libffmpegthumbnailer/videothumbnailerc.i: libffmpegthumbnailer/videothumbnailerc.cpp.i
.PHONY : libffmpegthumbnailer/videothumbnailerc.i

# target to preprocess a source file
libffmpegthumbnailer/videothumbnailerc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/videothumbnailerc.cpp.i
.PHONY : libffmpegthumbnailer/videothumbnailerc.cpp.i

libffmpegthumbnailer/videothumbnailerc.s: libffmpegthumbnailer/videothumbnailerc.cpp.s
.PHONY : libffmpegthumbnailer/videothumbnailerc.s

# target to generate assembly for a file
libffmpegthumbnailer/videothumbnailerc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libffmpegthumbnailerobj.dir/build.make CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/videothumbnailerc.cpp.s
.PHONY : libffmpegthumbnailer/videothumbnailerc.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpegthumbnailer.dir/build.make CMakeFiles/ffmpegthumbnailer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpegthumbnailer.dir/build.make CMakeFiles/ffmpegthumbnailer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpegthumbnailer.dir/build.make CMakeFiles/ffmpegthumbnailer.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... uninstall"
	@echo "... ffmpegthumbnailer"
	@echo "... ffmpegthumbnailerctest"
	@echo "... ffmpegthumbnailertest"
	@echo "... libffmpegthumbnailer"
	@echo "... libffmpegthumbnailerobj"
	@echo "... libffmpegthumbnailer/filmstripfilter.o"
	@echo "... libffmpegthumbnailer/filmstripfilter.i"
	@echo "... libffmpegthumbnailer/filmstripfilter.s"
	@echo "... libffmpegthumbnailer/jpegwriter.o"
	@echo "... libffmpegthumbnailer/jpegwriter.i"
	@echo "... libffmpegthumbnailer/jpegwriter.s"
	@echo "... libffmpegthumbnailer/moviedecoder.o"
	@echo "... libffmpegthumbnailer/moviedecoder.i"
	@echo "... libffmpegthumbnailer/moviedecoder.s"
	@echo "... libffmpegthumbnailer/pngwriter.o"
	@echo "... libffmpegthumbnailer/pngwriter.i"
	@echo "... libffmpegthumbnailer/pngwriter.s"
	@echo "... libffmpegthumbnailer/rgbwriter.o"
	@echo "... libffmpegthumbnailer/rgbwriter.i"
	@echo "... libffmpegthumbnailer/rgbwriter.s"
	@echo "... libffmpegthumbnailer/stringoperations.o"
	@echo "... libffmpegthumbnailer/stringoperations.i"
	@echo "... libffmpegthumbnailer/stringoperations.s"
	@echo "... libffmpegthumbnailer/videothumbnailer.o"
	@echo "... libffmpegthumbnailer/videothumbnailer.i"
	@echo "... libffmpegthumbnailer/videothumbnailer.s"
	@echo "... libffmpegthumbnailer/videothumbnailerc.o"
	@echo "... libffmpegthumbnailer/videothumbnailerc.i"
	@echo "... libffmpegthumbnailer/videothumbnailerc.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

